repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
- repo: https://github.com/qoomon/git-conventional-commits
  rev: v2.5.1
  hooks:
    - id: conventional-commits
