name: GitHub Actions Policy Testing
run-name: 
on: [push]
jobs:
  Explore-GitHub-Actions:
    if: "!contains(github.event.head_commit.message, 'aktion')"
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
